name: PhD Bibliography TeX compilation

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "main.pdf"

permissions:
  contents: write

jobs:
  build_tex_phd_beamer:

    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
    - uses: actions/checkout@v4

    - name: Build TeX
      run: |
        docker run --rm -v $PWD:/workspace -w /workspace texlive/texlive sh -c \
        "latexmk -interaction=nonstopmode -synctex=1 -pdf -bibtex main.tex"

    - name: Commit output PDF
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git switch --orphan pdf

        git rm -rf . || true

        git add -f main.pdf
        git commit -m "Update compiled PDF"
        git push origin pdf --force
